An exception occurred
Traceback (most recent call last):
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 390, in <module>
    main()
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 386, in main
    rc.report_cruk()
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 238, in report_cruk
    self.status = self.ml.data_entry.status
AttributeError: 'MyEntryWindow' object has no attribute 'status'
[CRITICAL ERROR]: 'MyEntryWindow' object has no attribute 'status'. See bioinformatics team for support [CRITICAL ERROR]


****[ERROR] PDF AND XML FILE HAVE NOT BEEN CORRECTLY GENERATED [ERROR]****
An exception occurred
Traceback (most recent call last):
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 396, in <module>
    main()
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 392, in main
    rc.report_cruk()
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 238, in report_cruk
    if not self.ml.data_entry.status or not self.ml.data_entry.sample or \
AttributeError: 'MyEntryWindow' object has no attribute 'status'
[CRITICAL ERROR]: 'MyEntryWindow' object has no attribute 'status'. See bioinformatics team for support [CRITICAL ERROR]


****[ERROR] PDF AND XML FILE HAVE NOT BEEN CORRECTLY GENERATED [ERROR]****
An exception occurred
Traceback (most recent call last):
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 239, in report_cruk
    self.ml.data_entry.status
AttributeError: 'MyEntryWindow' object has no attribute 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 399, in <module>
    main()
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 395, in main
    rc.report_cruk()
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 243, in report_cruk
    raise Exception("Data input was cancelled before all required data was entered.")
Exception: Data input was cancelled before all required data was entered.
[CRITICAL ERROR]: Data input was cancelled before all required data was entered.. See bioinformatics team for support [CRITICAL ERROR]


****[ERROR] PDF AND XML FILE HAVE NOT BEEN CORRECTLY GENERATED [ERROR]****
An exception occurred
Traceback (most recent call last):
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 239, in report_cruk
    self.ml.data_entry.status
AttributeError: 'MyEntryWindow' object has no attribute 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 399, in <module>
    main()
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 395, in main
    rc.report_cruk()
  File "/Users/sararey/PycharmProjects/CRUK_report/report_cruk.py", line 243, in report_cruk
    raise Exception("Data input was cancelled before all required data was entered")
Exception: Data input was cancelled before all required data was entered
[CRITICAL ERROR]: Data input was cancelled before all required data was entered. See bioinformatics team for support [CRITICAL ERROR]


****[ERROR] PDF AND XML FILE HAVE NOT BEEN CORRECTLY GENERATED [ERROR]****
